version: "3.9"

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile   
      target: build          
      args:
        CONFIG: development
    container_name: ionic-dev
    command: >
      npm start -- --host 0.0.0.0 --port 4200
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "10054:4200"   
      - "49153:49153" 
    environment:
      - CHOKIDAR_USEPOLLING=true
  prod:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        CONFIG: production
    container_name: ionic-prod
    ports:
      - "10055:80"
